---
- hosts: all
  become: yes
  tasks:
  - name: Clone RobotShop Git repo
    git:
      repo: "https://github.com/instana/robot-shop.git"
      dest: "/tmp/robotshop"
      update: yes

  - name: Deploy Docker Compose stack
    docker_compose:
      project_src: "/tmp/robotshop"
      files:
      - docker-compose.yaml
      - docker-compose-load.yaml
