---
- name: Install nginx
  hosts: all
  gather_facts: False
  become: true

  vars:
   - MyMessage: "Welcome to Think Lab 2176 instance!"

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html

  - file:
      path: /usr/share/nginx/html/index.html
      mode: 0644

  - name: Start NGiNX
    service:
      name: nginx
      state: started


